### ISSUE TITLE
Add a default resolver

### ISSUE THREAD

**Issue by watzon** [636f7374/carton.cr#1]
It would be nice to have a default resolver for the client and the server so that one doesn't have to be provided explicitly all the time. Maybe just use the exact same resolver that you set up in the examples with `1.1.1.1` and `8.8.8.8`.

**Comment by 636f7374** [comment]
@watzon 

* Actually it has a default DNS resolver server. => [src/durian/resolver.cr#L19](https://github.com/636f7374/durian.cr/blob/master/src/durian/resolver.cr#L19)
* In the examples just to demonstrate that you can customize the DNS server (feature) :)

**Comment by 636f7374** [comment]
@watzon Okay, this feature was added in 77ba1f3.

**Comment by watzon** [comment]
Awesome!
